lang = "en" # لغة البوت (ar للعربية أو en للإنجليزية)

[telegram]
token = "6819257727:AAH7t2kUypQKLMxvdZdvJw82tRyydBKWLFY"

# إعداد التخزين (سنستخدم ميزة إعادة الرفع إلى تيليجرام كأسهل طريقة لتجنب قيود هيروكو)
[[storages]]
name = "Telegram Cloud"
type = "telegram"
enable = true
chat_id = -1003459577535 # ضع آي دي القناة أو المجموعة التي تريد حفظ الملفات فيها (أو اتركه 0 ليرسلها لك في الخاص)

[[users]]
id = 5838811608 # ضع الآي دي الخاص بك في تيليجرام (مهم جداً لتكون الآدمن)
storages = ["Telegram Cloud"]
blacklist = true
